language: go

os:
  - linux
  - osx
  - windows

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

dist: bionic

go_import_path: github.com/desertbit/serial

env:
  - GOOS=linux GOARCH=386
  - GOOS=linux GOARCH=amd64
  - GOOS=linux GOARCH=arm
  - GOOS=windows GOARCH=386
  - GOOS=windows GOARCH=amd64
  - GOOS=darwin GOARCH=386
  - GOOS=darwin GOARCH=amd64
  - GOOS=freebsd GOARCH=amd64
  - GOOS=openbsd GOARCH=amd64
  - GOOS=openbsd GOARCH=386
  - GOOS=openbsd GOARCH=arm

matrix:
  allow_failures:
    - env: GOOS=openbsd GOARCH=arm

script:
  - GOARM=5 GO386=387 GOOS=$GOOS GOARCH=$GOARCH go build -v
  - GOARM=5 GO386=387 GOOS=$GOOS GOARCH=$GOARCH go test -c -v
  - if [[ $GOOS == "linux" && ($GOARCH == "386" || $GOARCH == "amd64") ]]; then GO386=387 GOOS=$GOOS GOARCH=$GOARCH go test -v ./...; fi


notifications:
  email:
    recipients:
      - desertbit@gmail.com
    on_success: change
    on_failure: always
